---

- name: Include special distribution-dependent variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install git and dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ git_package_names }}"

- name: Configure git
  include_tasks: git_user.yml
  with_dict:
  - "{{ git_users }}"